version: '3.7'

services:
  app_cherry:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    environment:
      - TZ=Asia/Seoul
  nginx_cherry:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "81:80"
      - "4413:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certbot/www:/var/www/certbot
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
    depends_on:
      - app_cherry
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul

  certbot:
    image: certbot/certbot
    volumes:
      - /home/ubuntu/certbot/www:/var/www/certbot
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
    #    entrypoint: "certbot certonly --webroot --webroot-path=/var/www/certbot --email wer1915@gmail.com --agree-tos --no-eff-email --staging -d k10b201.p.ssafy.io --rsa-key-size 2048"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx_cherry