#server:
#  port: 8060

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chelitalk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: update